name: flutter_assignment
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  http: ^0.13.4
  json_annotation: ^4.5.0
  stream_transform: ^2.0.0
  webview_flutter: ^3.0.4

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  mockito: ^5.2.0

flutter:
  uses-material-design: true
